version: '3'

services:
  mysql:
    image: mysql:8.0
    container_name: my_mysql_container
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - "3306:80"
    environment:
      DATABASE_URL: "mysql://root@127.0.0.1:3306/cc?charset=utf8mb4"
      MYSQL_ROOT_PASSWORD: ""  
      MYSQL_DATABASE: cc    
      MYSQL_USER: root        
      MYSQL_PASSWORD: ""  
    volumes:
      - mysql_data:/var/lib/mysql
    

volumes:
  mysql_data:
