FROM php:8.1-apache

RUN docker-php-ext-install pdo_mysql 

RUN curl -sSk https://getcomposer.org/installer | php -- -- disable-tts && \
    mv composer.phar /usr/local/bin/composer



COPY . /var/www


COPY ./docker/apache.conf/etc/apache2/BRIEF10SYMFONYAPI/000-default.conf


RUN cd /var/www && \
    composer install 


WORKDIR /var/www

ENTRYPOINT ["bash", "/docker/docker.sh"]

EXPOSE 80 